[Closes #157] Upgrade django (#175)
* Upgraded project to use latest django 4.2.x code (or higher, but not
5.anything).

Needed to update "django-postgres-setfield" as well to a custom
version that fixed a known issue with 'ugettext_lazy'. See:
https://code.djangoproject.com/ticket/30165.

Also regenerated the requirements.txt file per the above updates.

NOTES: In future, might want to update the Account model to have race
use models.JSONField() instead of this deprected SetField().

* After upgrade, got "(staticfiles.W004)" warning. Updated BASE_DIR
to fix and remove the warning.

Server log showed:
?: (staticfiles.W004) The directory '/app/server/settings.py/../../static'
   in the STATICFILES_DIRS setting does not exist.

* Using .astimezone(tz) instead of .localize(dt) in 2 files to fix:
AttributeError: 'zoneinfo.ZoneInfo' object has no attribute 'localize'

* Fixed test_export_users by changing assert to "text/csv".

Output from pytest:
E       AssertionError: 'application/octet-stream' != 'text/csv'
E       - application/octet-stream
E       + text/csv

* Fixed "AssertionError: Lists differ:" by changing how we freeze_time and
by using astimezone instead of utc.localize.

Ben Perlman had commented last year:

Modifying line 51 (removing ", tz_offset=-8):" from "with freeze_time("....") line)  allowed these two tests to pass, otherwise it failed as ["3000-03-02T00:00:00", 3], != ["3000-03-01T00:00:00", 3],

def test_get_home_users_daily(self):
self.assertEqual(
data,
[
["Date", "Count"],
["3000-02-28T00:00:00", 0],
["3000-03-02T00:00:00", 3],
["3000-03-14T00:00:00", 0],

def test_get_home_users_cumulative(self):
self.assertEqual(
data,
[
["Date", "Count"],
["3000-02-28T00:00:00", 0],
["3000-03-02T00:00:00", 3],
["3000-03-14T00:00:00", 3],

* Fixes DeprecationWarning: Please use assertEqual instead of self.assertEquals
(notice the singular vs the plural)